Repository googleapis/python-translate, pull requests merged in 2020-12, with the labels that each got.

#83 fix: moves import six inside of region tags
  samples/snippets/snippets.py
Labels: api: translate, cla: yes

#81 chore: require samples checks
  .github/sync-repo-settings.yaml
Labels: api: translate, automerge, cla: yes, samples

#89 chore: update testing and docs config
  .flake8
  .pre-commit-config.yaml
  CONTRIBUTING.rst
  docs/conf.py
  docs/translate_v3/types.rst
  docs/translate_v3beta1/types.rst
  google/cloud/translate_v3/services/translation_service/async_client.py
  google/cloud/translate_v3/services/translation_service/client.py
  google/cloud/translate_v3/services/translation_service/transports/__init__.py
  google/cloud/translate_v3/services/translation_service/transports/grpc.py
  google/cloud/translate_v3/services/translation_service/transports/grpc_asyncio.py
  google/cloud/translate_v3/types/__init__.py
  google/cloud/translate_v3/types/translation_service.py
  google/cloud/translate_v3beta1/services/translation_service/async_client.py
  google/cloud/translate_v3beta1/services/translation_service/client.py
  google/cloud/translate_v3beta1/services/translation_service/transports/__init__.py
  google/cloud/translate_v3beta1/services/translation_service/transports/base.py
  google/cloud/translate_v3beta1/services/translation_service/transports/grpc.py
  google/cloud/translate_v3beta1/services/translation_service/transports/grpc_asyncio.py
  google/cloud/translate_v3beta1/types/__init__.py
  google/cloud/translate_v3beta1/types/translation_service.py
  noxfile.py
  samples/snippets/hybrid_glossaries/noxfile.py
  samples/snippets/noxfile.py
  scripts/fixup_translate_v3_keywords.py
  scripts/fixup_translate_v3beta1_keywords.py
  synth.metadata
  tests/unit/gapic/translate_v3/test_translation_service.py
  tests/unit/gapic/translate_v3beta1/test_translation_service.py
Labels: api: translate, cla: yes, context: partial

#90 chore: add tarfile
  synth.metadata
  translation-v3-py.tar.gz
Labels: api: translate, cla: yes, context: none
