Repository googleapis/python-translate, pull requests merged in 2020-08, with the labels that each got.

#28 chore: updates build templates (docs-presubmit)
  .gitignore
  .kokoro/build.sh
  .kokoro/docker/docs/Dockerfile
  .kokoro/docker/docs/fetch_gpg_keys.sh
  .kokoro/docs/common.cfg
  .kokoro/docs/docs-presubmit.cfg
  .kokoro/publish-docs.sh
  .kokoro/trampoline_v2.sh
  .trampolinerc
  docs/conf.py
  noxfile.py
  synth.metadata
Labels: automerge, cla: yes, context: full

#35 chore: config template changes from synthtool
  .kokoro/docker/docs/Dockerfile
  docs/conf.py
  synth.metadata
Labels: automerge, cla: yes, context: partial

#38 chore: applies new samples README template
  samples/snippets/hybrid_glossaries/README.rst
  synth.metadata
Labels: cla: yes, context: none

#39 fix: update retry and timeout config
  .coveragerc
  docs/translate_v3/services.rst
  docs/translate_v3/types.rst
  docs/translate_v3beta1/services.rst
  docs/translate_v3beta1/types.rst
  google/cloud/translate/py.typed
  google/cloud/translate_v3/py.typed
  google/cloud/translate_v3/services/translation_service/async_client.py
  google/cloud/translate_v3/services/translation_service/client.py
  google/cloud/translate_v3/services/translation_service/transports/base.py
  google/cloud/translate_v3beta1/py.typed
  google/cloud/translate_v3beta1/services/translation_service/async_client.py
  google/cloud/translate_v3beta1/services/translation_service/client.py
  google/cloud/translate_v3beta1/services/translation_service/transports/base.py
  scripts/fixup_translate_v3_keywords.py
  scripts/fixup_translate_v3beta1_keywords.py
  setup.py
  synth.metadata
  synth.py
Labels: cla: yes

#48 test(samples): change string for utf8 translation
  samples/snippets/snippets_test.py
Labels: automerge, cla: yes

#54 test: fix vpcsc tests
  tests/system/test_vpcsc.py
Labels: api: translate, cla: yes

#57 samples: fixed flaky test
  samples/snippets/hybrid_glossaries/hybrid_tutorial.py
  samples/snippets/hybrid_glossaries/hybrid_tutorial_test.py
Labels: api: translate, cla: yes
