Repository googleapis/python-translate, pull requests merged in 2020-09, with the labels that each got.

#58 test: remove usage of location_path
  tests/system/test_vpcsc.py
Labels: api: translate, cla: yes

#63 chore: update version to latest
  samples/snippets/requirements.txt
Labels: api: translate, automerge, cla: yes

#66 fix: adjusts flaky test; deletes unneeded test
  samples/snippets/hybrid_glossaries/hybrid_tutorial_test.py
  samples/snippets/hybrid_glossaries/resources/non_standard_format.png
  samples/snippets/hybrid_glossaries/resources/non_standard_format.txt
Labels: cla: yes

#65 test: fix broken vpcsc tests
  tests/system/test_vpcsc.py
Labels: api: translate, automerge, cla: yes

#70 chore: add default CODEOWNERS
  .github/CODEOWNERS
Labels: api: translate, cla: yes
