Repository googleapis/python-translate, pull requests merged in 2021-04, with the labels that each got.

#130 chore: remove tar.gz
  synth.metadata
  translation-v3-py.tar.gz
Labels: cla: yes, context: none

#132 chore: Add license headers for python config files
  .pre-commit-config.yaml
  docs/conf.py
  synth.metadata
Labels: api: translate, automerge, cla: yes, context: full

#135 chore: prevent normalization of semver versioning
  setup.py
Labels: api: translate, cla: yes

#137 chore: migrate to owl bot
  .coveragerc
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
  .github/header-checker-lint.yml
  .kokoro/release.sh
  .kokoro/release/common.cfg
  docs/_static/custom.css
  owlbot.py
  renovate.json
  samples/snippets/hybrid_glossaries/noxfile.py
  samples/snippets/noxfile.py
  synth.metadata
Labels: api: translate, automerge, cla: yes

#139 chore(revert): revert preventing normalization
  setup.py
Labels: api: translate, cla: yes
