Repository googleapis/python-translate, pull requests merged in 2022-04, with the labels that each got.

#368 chore: allow releases on previous majors
  .github/release-please.yml
  owlbot.py
Labels: api: translate, size: s

#353 fix(deps): require google-api-core >= 1.31.5, >= 2.3.2 on v2 release
  docs/conf.py
  google/cloud/translate_v3/gapic/translation_service_client.py
  google/cloud/translate_v3/proto/translation_service_pb2.py
  google/cloud/translate_v3/proto/translation_service_pb2_grpc.py
  google/cloud/translate_v3beta1/gapic/translation_service_client.py
  google/cloud/translate_v3beta1/proto/translation_service_pb2.py
  google/cloud/translate_v3beta1/proto/translation_service_pb2_grpc.py
  noxfile.py
  setup.py
  tests/system.py
  tests/unit/v2/test__http.py
  tests/unit/v2/test_client.py
Labels: api: translate

#354 fix(deps): require google-api-core >= 1.31.5, >= 2.3.2 on v1 release
  docs/conf.py
  google/cloud/translate_v3/gapic/translation_service_client.py
  google/cloud/translate_v3/proto/translation_service_pb2_grpc.py
  google/cloud/translate_v3beta1/gapic/translation_service_client.py
  google/cloud/translate_v3beta1/proto/translation_service_pb2_grpc.py
  noxfile.py
  setup.py
  tests/system.py
  tests/unit/test_client.py
Labels: api: translate

#371 chore: add trampoline for release script
  .kokoro/populate-secrets.sh
  .kokoro/trampoline.sh
Labels: api: translate, size: m

#384 test: remove flaky test case in system test
  tests/system.py
Labels: api: translate, size: xs
